sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/chart --watch=false
  - npx ng build @angeeks/chart --prod
  - npx ng test chart --watch=false
  - npx ng build chart --prod --base-href chart
cache:
    directories:
      - node_modules
before_deploy:
  - pwd
  - ls
  - cp README.md dist/angeeks/chart
  - cd dist/angeeks/chart
deploy:
  - provider: npm
    email: $npmEmail
    api_key: $npm
    skip_cleanup: true
    keep-history: true
    tag: latest
    on:
      branch: release
notifications:
  email:
    - $notifyEmail
  slack:
    - secure: $slackToken
