sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
before_script:
  - npx ng lint @angeeks/chart
  - npx ng test @angeeks/chart
  - npx ng build @angeeks/chart --prod
  - npm run lint
  - npm run test
  - npx ng build --prod
cache:
    directories:
      - node_modules
deploy:
  skip-cleanup: true
  github-token: '$token'
  keep-history: true
  provider: pages
  local-dir: dist/chart
